config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'entities#index'
  resources :entities, only: %i[show index]
  resources :variables, only: %i[show index]
  # get "/:page" => "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
# frozen_string_literal: true

class Entity < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  has_many :roles
  has_many :variables

  def to_s
    name || ''
  end
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  belongs_to :entity

  def to_s
    "#{entity.name}.#{name}"
  end
end

app/models/value_type.rb
# frozen_string_literal: true

class ValueType < ApplicationRecord
  has_many :variables
end

app/models/variable.rb
# frozen_string_literal: true

class Variable < ApplicationRecord
  validates :name, presence: true
  validates :entity, presence: true
  translates :description
  extend FriendlyId
  friendly_id :name

  belongs_to :value_type
  belongs_to :entity

  has_and_belongs_to_many(:variables,
                          class_name: 'Variable',
                          join_table: 'links',
                          foreign_key: 'link_to',
                          association_foreign_key: 'link_from')

  has_and_belongs_to_many(:reversed_variables,
                          class_name: 'Variable',
                          join_table: 'links',
                          foreign_key: 'link_from',
                          association_foreign_key: 'link_to')

  def has_formula?
    spec['formulas'].present?
  end

  def github_url
    "#{ENV['GITHUB_URL']}#{spec['source'].gsub('//', '/tree/master/').gsub('blob', '').gsub('/app/', '/')}"
  rescue StandardError
    nil
  end

  def to_s
    name
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
# frozen_string_literal: true

class EntitiesController < ApplicationController
  def index
    @entities = Entity.all.includes(:variables).order(:name)
  end

  def show
    @entity = Entity.find_by(name: params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ActionController::Base
  def show
    render 'about'
  end
end

app/controllers/variables_controller.rb
# frozen_string_literal: true

class VariablesController < ApplicationController
  before_action :set_variable, only: %i[show edit update destroy]
  def index
    @search = VariablesSearchService.new(params)

    @variables = @search.result
                        .distinct(false)
                        .includes(:variables, :value_type, :entity)
                        .order(:name)

    # Get the links between variables (both directions)
    # in just 2 quick db queries
    @link_from_counts = link_count(:variables, :link_from)
    @link_to_counts = link_count(:reversed_variables, :link_to)

    @namespace_filter = @search.filter(:namespace)
  end

  def show; end

  private

  def link_count(relationship, column)
    Variable.all.joins(relationship).group(column).count
  end

  def set_variable
    @variable = Variable.find_by(name: params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def render_markdown(content)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})
    markdown.render(content).html_safe
  end
end

app/helpers/entities_helper.rb
# frozen_string_literal: true

module EntitiesHelper
end

app/helpers/variables_helper.rb
# frozen_string_literal: true

module VariablesHelper
  def display_formula(formula)
    Variable.all.each do |v|
      formula.gsub!("'#{v.name}'", "<strong>'#{link_to(v.name, v)}'</strong>")
      formula.gsub!("\"#{v.name}\"", "<strong>'#{link_to(v.name, v)}'</strong>")
    end
    formula.html_safe
  end

  def url?(string)
    string =~ /\A#{URI::DEFAULT_PARSER.make_regexp}\z/
  end
end

app/views/entities/_badges.html.haml
- if entity.variables.size.positive?
  %span.badge.badge-dark #{pluralize entity.variables.size, 'variable'}

- if entity.roles.size.positive?
  %span.badge.badge-dark #{pluralize entity.roles.size, 'role'}


-#   - if entity.namespace.present?
-#     %span.badge.badge-primary= t entity.namespace.to_sym

-#   %span.badge.badge-secondary=entity.value_type.name

-#   %span.badge.badge-secondary=entity.spec['definitionPeriod']

-#   - if entity.entity.present?
-#     %span.badge.badge-success= t entity.entity.name.to_sym

-#   - if entity.has_formula?
-#     %span.badge.badge-info= t :formula_included
-#   - elsif entity.entitys.size == 0
-#     %span.badge.badge-warning{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'Not used by any formula, and has no formula itself'}= t :orphaned

-#   - unless entity.description
-#     %span.badge.badge-danger{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'No label defined for this entity'}= t :label_missing

app/views/entities/index.html.haml
.container
  .card-columns
    - @entities.each do |entity|
      .card.w-33
        .card-body
          %h5.card-title
            = link_to entity.to_s.capitalize, entity
          = render 'badges', entity: entity
          %p.card-text
            = render_markdown(entity.documentation) if entity.documentation.present?
          %h5= t(:example_variables)
          %ul.list-group.list-group-flush
            - entity.variables.limit(5).order("RANDOM()").each do |v|
              %li.list-group-item
                = t v.namespace
                = link_to v.description, v

app/views/entities/show.html.haml
.container
  %h1= @entity.description
  = render 'badges', entity: @entity

  %p
    = render_markdown(@entity.documentation) if @entity.documentation.present?


  - if @entity.roles.size.positive?
    %h2 Roles within #{@entity.description}

    .card-columns
      - @entity.roles.each do |role|
        .card{:style => "width: 18rem;"}
          .card-body
            %h5.card-title= role.name
            %p.card-text= role.description


  %h3.page-heading= t(:variables_that_you_can_set, entity_description: @entity.description)

  .card-columns
    - @entity.variables.order(:namespace, :name).each do |variable|
      = render 'variables/card', variable: variable

app/views/layouts/_alerts.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/_explanation.haml
%header.header
  .container
    .hero
      %h1= t(:rapu_ture_exploring_the_rules)
      %p= t :variables_explanation
      = image_tag('beehive.svg', alt: 'A scalable vector image of the New Zealand Government Beehive', class: 'logo')

    .header-secondary
      %h2= t(:rapu_ture_explanation)
      = link_to 'https://www.digital.govt.nz/blog/global-coverage-of-our-legislation-as-code-work/', class: 'btn btn-primary btn-lg', role: 'button' do
        Learn more

app/views/layouts/_sub_header.haml
.sub-header
  .container
    = link_to root_path do
      %h1= t(:rapu_ture_exploring_the_rules)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = t(:rapu_ture_connecting_the_rules)
      = yield :title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/


  %body

    =# import alerts here

    - if current_page?(root_url)
      = render 'layouts/explanation'
    - else
      = render 'layouts/sub_header'

    %main
      .btn-nav
        .container
          = link_to t(:explore_by_variables), variables_path, class: 'btn'
          = link_to t(:explore_by_entities), entities_path, class: 'btn'
        .container
          =yield :breadcrumbs


      = yield

  %footer
    .container
      %p
        %span
          = t(:computations_powered_by)
          = succeed ',' do
            %a{href: "https://openfisca.org", rel: "noopener", target: "_blank"}
              %img{alt: "OpenFisca", height: "24", src: "https://openfisca.org/img/logo-openfisca.svg"}/
          %a{href: "https://github.com/openfisca/openfisca-core"} source code
          is used under an
          %a{href: "https://choosealicense.com/licenses/agpl-3.0/", rel: "noopener", target: "_blank"} AGPL license.

app/views/layouts/pages.html.haml
!!!
%html
  %head
    %title
      = t(:rapu_ture_connecting_the_rules)
      = yield :title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    %meta{ content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport' }/


  %body
    = render 'layouts/sub_header'
    = yield

  %footer
    .container
      %p
        %span
          = t(:computations_powered_by)
          = succeed ',' do
            %a{ href: 'https://openfisca.org', rel: 'noopener', target: '_blank' }
              %img{ alt: 'OpenFisca', height: '24', src: 'https://openfisca.org/img/logo-openfisca.svg' }/
          %a{ href: 'https://github.com/openfisca/openfisca-core' } source code
          is used under an
          %a{ href: 'https://choosealicense.com/licenses/agpl-3.0/', rel: 'noopener', target: '_blank' } AGPL license.

app/views/pages/about.html.haml
%main
  .container
    .row
      .col-lg-3
        %ul.side-nav.list-stripped
          %li= link_to t(:what_is_raputure), '#q1'
          %li= link_to t(:what_is_legislation_of_code)
          %li= link_to t(:how_to_use_rapu_ture), '#q3'
          %li= link_to t(:how_to_contribute)
          %li= link_to t(:contact_us)

      .col-lg-9
        %section.section
          %h1.heading= t(:what_is_rapu_ture)
          %h2.heading-secondary= t(:rapu_ture_explanation)

          %dl
            %dt#q1= t(:what_is_legislation_of_code)
            %dd= t(:legislation_of_code_explanation)


            %dt= t(:how_to_use_rapu_ture)
            %dd= t(:how_to_use_rapu_ture_explanation)

            %dt= t(:how_to_contribute)
            %dd= t(:how_to_contribute_explanation)

            %dt= t(:contact_us)
            %dd= t(:contact_us_explanation)

app/views/variables/_badges.haml
- cache variable do
  - if variable.namespace.present?
    %span.badge.badge-primary= t variable.namespace.to_sym

  %span.badge.badge-secondary=variable.value_type.name

  %span.badge.badge-secondary=t variable.spec['definitionPeriod']

  - if variable.entity.present?
    %span.badge.badge-success= link_to t(variable.entity.name), variable.entity

  - if variable.has_formula?
    %span.badge.badge-info= t :formula_included

  - if link_to_count.zero? && link_from_count.zero?
    %span.badge.badge-warning{ 'data-toggle': 'tooltip',
      'data-placement': 'bottom', title: 'Not used by any formula, and has no formula itself' }
      Orphaned
  - else
    %span.badge.badge-dark used #{pluralize link_to_count, 'time'}


  - unless variable.description
    %span.badge.badge-danger{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'No label defined for this variable'}= t :label_missing

app/views/variables/_card.haml
- cache variable do
  .card
    .card-body
      %h5.card-title= link_to variable.name, variable
      %p.card-text=variable.description
      = render 'variables/badges', variable: variable,
        link_to_count: link_to_count.to_i, link_from_count: link_from_count.to_i

app/views/variables/_filters.haml
.container
  - if @namespace_filter.selected.size.positive?
    %h6= t(:current_filters)
    %p
      - @namespace_filter.selected.each do |namespace|
        = link_to @namespace_filter.remove(namespace).path, class: 'filter-select' do
          = t(namespace.to_sym)
          = fa_icon 'close'

  %h6= t(:available_filters_to_use, namespace_filter_name: @namespace_filter.name)
  %p
    - @namespace_filter.facet.reject(&:selected).each do |facet_value|
      - if facet_value.entity
        = link_to @namespace_filter.add(facet_value.entity).path, class: 'filter-select' do
          = fa_icon 'plus'
          = t(facet_value.entity.to_sym)
          %span.count= "(#{facet_value.count})"

app/views/variables/_link.haml
%span.badge.badge-secondary=variable.value_type.name
= link_to variable.name, variable
= variable.description

app/views/variables/_references.haml
- if variable.variables.size.positive?
  %ul.list-bulleted
    - variable.variables.order(:name).each do |v|
      %li{class: v.value_type.name}
        = render 'link', variable: v
      = render 'references', variable: v

app/views/variables/index.html.haml
%p#notice= notice

= render 'filters'

.container
  .card-columns
    - @variables.each do |variable|
      = render 'card', variable: variable,
        link_to_count: @link_to_counts[variable.id],
        link_from_count: @link_from_counts[variable.id]

app/views/variables/show.html.haml
.container
  - content_for(:title) do
    = @variable.name

  - content_for(:breadcrumbs) do
    %ul.list-stripped.list-inline.breadcrumbs
      - if @variable.namespace.present?
        %li.breadcrumb-item
          = t @variable.namespace.to_sym
      %li.breadcrumb-item.active{"aria-current" => "page"}= @variable.name


  %h3
    -if @variable.description
      = @variable.description
    - else
      = @variable.name
  = render 'badges', variable: @variable,
    link_to_count: @variable.reversed_variables.size,
    link_from_count: @variable.variables.size

  %hr/

  %p
    %strong= t :value_type
    = @variable.value_type.name
    \.
    %strong=t :default_value
    = @variable.spec['defaultValue']
    %strong=t :entity
    = @variable.spec['entity']

  - cache @variable do
    - if @variable.variables.size.positive?
      %hr/
      %h3= t :references
      %p= t :references_explanation
      = render 'references', variable: @variable
    - if @variable.reversed_variables.size.positive?
      %hr/
      %h3=t :referenced_by
      %p=t :referenced_explanation
      %ul
        - @variable.reversed_variables.order(:name).each do |v|
          %li= render 'link', variable: v

    - if @variable.has_formula?
      %hr/
      %h3=t :formulas
      %p
        = t :formula_explanation, name: @variable.name
        - @variable.spec['formulas'].each do |d, formula|
          %h3= d
          %p
            = t(:formula_for_scenarios_from_date_onwards, formula_date: d)
            = link_to 'More info on formulas', 'https://openfisca.org/doc/coding-the-legislation/10_basic_example.html'
          %pre= display_formula formula['content']


    %hr/
    %ul.nav
      - if @variable.references.present?
        - @variable.references.each do |ref|
          - if url?(ref)
            %li= link_to t(:reference), ref, class: 'nav-link'
          - else
            %li.nav-link Source: #{ref}
      - if @variable.spec.present?
        %li= link_to 'Source Code', @variable.github_url, class: 'nav-link'
      %li= link_to t(:view_api), @variable.href, class: 'nav-link'